In [1]:
# Normalise features
# Find the optimal parameters C (inverse regulalisation strengths)
# Find the best features to predict stock movement (up or down)
# Convert probability into absolute values (stock % increase/decrease)
# SVC, RandomForest, MinMax, LongShortTermMemory

%matplotlib inline
%pylab inline

# Nice Formatting within Jupyter Notebook
%matplotlib inline
from IPython.display import display # Allows multiple displays from a single code-cell
from jupyterthemes import jtplot

#import classes
from utilities import *
from company import Company
from onestep_baseline_company import OneStepBaselineCompany
from onestep_lstm_company import OneStepLSTMCompany
from multistep_baseline_company import MultiStepBaselineCompany
from multistep_lstm_company import MultiStepLSTMCompany

jtplot.style(theme='grade3')
jtplot.style(theme='grade3')
jtplot.style(theme='grade3')


Populating the interactive namespace from numpy and matplotlib


Using TensorFlow backend.


In [2]:
"""import tensorflow as tf
import os
from keras import backend as K
config = tf.ConfigProto(intra_op_parallelism_threads=NUM_PARALLEL_EXEC_UNITS, inter_op_parallelism_threads=2,
                        allow_soft_placement=True, device_count={'CPU': NUM_PARALLEL_EXEC_UNITS})

session = tf.Session(config=config)
K.set_session(session)
os.environ["OMP_NUM_THREADS"] = "NUM_PARALLEL_EXEC_UNITS"
os.environ["KMP_BLOCKTIME"] = "30"
os.environ["KMP_SETTINGS"] = "1"
os.environ["KMP_AFFINITY"] = "granularity=fine,verbose,compact,1,0"
"""
start_train_date = "01/01/2015"
end_train_start_test_date = "10/01/2015"
end_test_date = "01/03/2015"

obj = MultiStepLSTMCompany("AAPL", start_train_date, end_train_start_test_date, end_test_date, 
                         n_lag=3, n_seq=3, n_epochs=3000, n_batch=1, n_neurons=4, tech_indicators=["sma"], model_type="vanilla")
obj.train()

Preprocessing the data
Retrieved price series and raw pd from disk
Preprocessed data in  0.0016157031059265137 mins
Fitting the model
train size 6
train X data [[[ 0.94180171  0.26158445]
  [-0.26037985  1.        ]
  [-0.73961549  0.42368046]]

 [[ 0.0938491   1.        ]
  [-0.5886234   0.49177877]
  [-0.43764822 -0.2467903 ]]

 [[-0.39160132  0.49177877]
  [-0.11155097 -0.21076233]
  [-1.         -1.        ]]

 [[ 0.31395714 -0.21076233]
  [-1.         -1.        ]
  [-0.14403329 -0.85734665]]

 [[-1.         -1.        ]
  [ 0.35232575 -0.85052317]
  [ 0.26591794  0.30955777]]

 [[ 1.         -0.85052317]
  [ 1.          0.37219731]
  [ 1.          1.        ]]]
train y data [[-0.43764822 -1.         -0.19709715]
 [-1.         -0.14403329  0.2318689 ]
 [-0.14403329  0.26591794  1.        ]
 [ 0.26591794  1.         -0.16519703]
 [ 1.         -0.11354721 -1.        ]
 [-0.11354721 -0.91134577  0.08113929]]
Trained model with batch size 1
____________________________________________

ValueError: Error when checking input: expected lstm_2_input to have shape (3, 2) but got array with shape (1, 6)

In [ ]:
#start_train_date = "01/01/2010"
#end_train_start_test_date = "01/01/2015"
#end_test_date = "01/01/2020"
#obj.update_train_test_set(start_train_date, end_train_start_test_date, end_test_date)
predictions = obj.predict()

trend_score = obj.score(metric="trend", predictions=predictions)

lstm_score = obj.score(metric="rmse", predictions=predictions)
apre_score = obj.score(metric="apre", predictions=predictions)
print("LSTM trend Score: ", trend_score)
print("LSTM RMSE Score: US dollar", lstm_score)
print("LSTM APRE Score: US dollar", apre_score)

In [ ]:
obj2 = MultiStepLSTMCompany("AAPL", start_train_date, end_train_start_test_date, end_test_date, 
                         n_lag=3, n_seq=3, n_epochs=3000, n_batch=17, n_neurons=4, tech_indicators="all", model_type="conv")
obj2.train()

In [ ]:
predictions = obj2.predict()
apre_score = obj2.score(metric="apre", predictions=predictions)
trend_score = obj2.score(metric="trend", predictions=predictions)
rmsq_score = obj2.score(metric="rmse", predictions=predictions)
print("LSTM trend Score: ", trend_score)
print("LSTM RMSE Score: US dollar", rmsq_score)
print("LSTM APRE Score: US dollar", apre_score)


In [ ]:
obj3 = MultiStepLSTMCompany("AAPL", start_train_date, end_train_start_test_date, end_test_date, 
                         n_lag=3, n_seq=3, n_epochs=3000, n_batch=17, n_neurons=4, tech_indicators="all", model_type="bi")
obj3.train()

In [ ]:
predictions = obj3.predict()
apre_score = obj3.score(metric="apre", predictions=predictions)
trend_score = obj3.score(metric="trend", predictions=predictions)
rmsq_score = obj3.score(metric="rmse", predictions=predictions)
print("LSTM trend Score: ", trend_score)
print("LSTM RMSE Score: US dollar", rmsq_score)
print("LSTM APRE Score: US dollar", apre_score)

In [ ]:
#obj3.supervised_pd.shape[2]