In [1]:
# Normalise features
# Find the optimal parameters C (inverse regulalisation strengths)
# Find the best features to predict stock movement (up or down)
# Convert probability into absolute values (stock % increase/decrease)
# SVC, RandomForest, MinMax, LongShortTermMemory

%matplotlib inline
%pylab inline

# Nice Formatting within Jupyter Notebook
%matplotlib inline
from IPython.display import display # Allows multiple displays from a single code-cell
from jupyterthemes import jtplot

#import classes
from utilities import *
from company import Company
from onestep_baseline_company import OneStepBaselineCompany
from onestep_lstm_company import OneStepLSTMCompany
from multistep_baseline_company import MultiStepBaselineCompany
from multistep_lstm_company import MultiStepLSTMCompany

jtplot.style(theme='grade3')
jtplot.style(theme='grade3')
jtplot.style(theme='grade3')


Populating the interactive namespace from numpy and matplotlib


Using TensorFlow backend.


In [2]:
start_train_date = "01/04/2017"
end_train_start_test_date = "10/04/2017"
end_test_date = "20/04/2017"

obj = MultiStepLSTMCompany("MU", start_train_date, end_train_start_test_date, end_test_date, 
                         n_lag=3, n_seq=3, n_epochs=3000, n_batch=1, n_neurons=4, tech_indicators=["sma", "rsi"])
obj.train()

Preprocessing the data
Fitting the model


'train X data'

array([[[-0.65      ,  0.53956835, -0.41415308,  1.        ,
          1.        ,  0.99917509, -0.24637681,  0.52542373,
          0.02709837]],

       [[ 1.        ,  1.        ,  1.        , -0.35      ,
         -0.35251799,  0.02709837, -0.79710145, -0.83050847,
         -0.71713755]],

       [[-0.35      , -0.35251799,  0.02752218, -0.825     ,
         -0.92805755, -0.71713755, -0.1884058 , -0.76271186,
          0.10138173]],

       [[-0.825     , -0.92805755, -0.71702084, -0.3       ,
         -0.89928058,  0.10138173, -1.        , -1.        ,
         -1.        ]],

       [[-0.3       , -0.89928058,  0.10183619, -1.        ,
         -1.        , -1.        ,  1.        ,  1.        ,
          1.        ]],

       [[-1.        , -1.        , -1.        ,  0.725     ,
         -0.15107914,  1.        , -0.33333333,  0.55932203,
         -0.10121675]]])

'train y data'

array([[ 2.94209102e-15,  3.38709677e-01, -1.12903226e-01],
       [ 3.38709677e-01, -1.12903226e-01,  1.00000000e+00],
       [-1.12903226e-01,  1.00000000e+00,  2.58064516e-01],
       [ 1.00000000e+00,  2.58064516e-01, -1.00000000e+00],
       [ 2.58064516e-01, -1.00000000e+00, -3.22580645e-01],
       [-1.00000000e+00, -3.22580645e-01, -3.70967742e-01]])

Finished fitting the model, time taken to train: 28.7 s
Saving object and model


In [3]:
display(obj.supervised_pd)
display(obj.train_raw_series)
display(obj.test_raw_series)

Share Price(t-3)  SMA(t-3)  RSI(t-3)  Share Price(t-2)  SMA(t-2)  \
date                                                                           
2017-04-03             -0.19    0.1975   -1.7286              0.47    0.2135   
2017-04-04              0.47    0.2135    1.6986             -0.07    0.1665   
2017-04-05             -0.07    0.1665   -0.6582             -0.26    0.1465   
2017-04-06             -0.26    0.1465   -2.4626             -0.05    0.1475   
2017-04-07             -0.05    0.1475   -0.4781             -0.33    0.1440   
2017-04-10             -0.33    0.1440   -3.1484              0.36    0.1735   
2017-04-11              0.36    0.1735    1.7006             -0.10    0.1670   
2017-04-12             -0.10    0.1670   -0.9693             -0.88    0.0970   
2017-04-13             -0.88    0.0970   -7.8115             -0.46    0.0800   
2017-04-17             -0.46    0.0800   -3.5638             -0.49    0.0285   
2017-04-18             -0.49    0.0285   -3.5147              0.05    0.0350   
2017-04-19              0.05    0.0350    0.3282              0.39    0.0665   
2017-04-20              0.39    0.0665    2.5347              0.01    0.0465   

            RSI(t-2)  Share Price(t-1)  SMA(t-1)  RSI(t-1)  Share Price(t)  \
date                                                                         
2017-04-03    1.6986             -0.07    0.1665   -0.6582           -0.26   
2017-04-04   -0.6582             -0.26    0.1465   -2.4626           -0.05   
2017-04-05   -2.4626             -0.05    0.1475   -0.4781           -0.33   
2017-04-06   -0.4781             -0.33    0.1440   -3.1484            0.36   
2017-04-07   -3.1484              0.36    0.1735    1.7006           -0.10   
2017-04-10    1.7006             -0.10    0.1670   -0.9693           -0.88   
2017-04-11   -0.9693             -0.88    0.0970   -7.8115           -0.46   
2017-04-12   -7.8115             -0.46    0.0800   -3.5638           -0.49   
2017-04-13   -3.5638             -0.49    0.0285   -3.5147            0.05   
2017-04-17   -3.5147              0.05    0.0350    0.3282            0.39   
2017-04-18    0.3282              0.39    0.0665    2.5347            0.01   
2017-04-19    2.5347              0.01    0.0465    0.0647            0.12   
2017-04-20    0.0647              0.12    0.0870    0.8018            0.70   

            Share Price(t+1)  Share Price(t+2)  
date                                            
2017-04-03             -0.05             -0.33  
2017-04-04             -0.33              0.36  
2017-04-05              0.36             -0.10  
2017-04-06             -0.10             -0.88  
2017-04-07             -0.88             -0.46  
2017-04-10             -0.46             -0.49  
2017-04-11             -0.49              0.05  
2017-04-12              0.05              0.39  
2017-04-13              0.39              0.01  
2017-04-17              0.01              0.12  
2017-04-18              0.12              0.70  
2017-04-19              0.70             -0.64  
2017-04-20             -0.64             -0.75

date
2017-04-03    28.64
2017-04-04    28.59
2017-04-05    28.26
2017-04-06    28.62
2017-04-07    28.52
2017-04-10    27.64
Name: Share Price, dtype: float64

date
2017-04-11    27.18
2017-04-12    26.69
2017-04-13    26.74
2017-04-17    27.13
2017-04-18    27.14
2017-04-19    27.26
2017-04-20    27.96
Name: Share Price, dtype: float64

In [4]:
predictions = obj.predict()

trend_score = obj.score(metric="trend", predictions=predictions)
print("LSTM trend Score: ", trend_score)
lstm_score = obj.score(metric="rmse", predictions=predictions)
print("LSTM RMSE Score: US dollar", lstm_score)

index DatetimeIndex(['2017-04-11', '2017-04-12', '2017-04-13', '2017-04-17',
               '2017-04-18', '2017-04-19', '2017-04-20'],
              dtype='datetime64[ns]', name='date', freq=None)
X:  [ 0.725      -0.15107914  1.00082525 -0.425      -0.3381295  -0.10121675
 -2.5942029  -4.18644068 -2.9233244 ] y:  [-0.32258065 -0.37096774  0.5       ]  pred:  [1.3411045, -0.5484847, -1.962237]
X:  [-0.425      -0.3381295  -0.10084588 -2.375      -2.35251799 -2.9233244
 -1.37681159 -5.33898305 -1.1713343 ] y:  [-0.37096774  0.5         1.0483871 ]  pred:  [1.4874412, -0.6487383, -2.1164753]
X:  [-2.375      -2.35251799 -2.92411801 -1.325      -2.84172662 -1.1713343
 -1.46376812 -8.83050847 -1.1510827 ] y:  [0.5        1.0483871  0.43548387]  pred:  [1.7569661, -0.7168004, -2.1328502]
X:  [-1.325      -2.84172662 -1.17140499 -1.4        -4.32374101 -1.1510827
  0.10144928 -8.38983051  0.43394514] y:  [1.0483871  0.43548387 0.61290323]  pred:  [1.3284309, -0.63596493, -2.1595411]
X:  [-1.

'actual'

array([[27.18, 26.69, 26.74],
       [26.69, 26.74, 27.13],
       [26.74, 27.13, 27.14],
       [27.13, 27.14, 27.26],
       [27.14, 27.26, 27.96]])

'predicted'

array([[28.21148479, 27.61142429, 26.13483735],
       [27.84221353, 27.17999577, 25.60778106],
       [27.51931899, 26.81490275, 25.23253564],
       [27.30362715, 26.6493289 , 25.0504134 ],
       [26.95713351, 26.42151145, 25.05251354]])


Calculating trend score for  1
Price 1 day before:  27.64
Actual price:  27.18  | Predicted price:  28.2114847946167
Actual trend:  down  | Predicted trend:  up
Price 1 day before:  27.18
Actual price:  26.69  | Predicted price:  27.84221353292465
Actual trend:  down  | Predicted trend:  up
Price 1 day before:  26.69
Actual price:  26.74  | Predicted price:  27.519318990707397
Actual trend:  up  | Predicted trend:  up
Price 1 day before:  26.74
Actual price:  27.13  | Predicted price:  27.303627152442928
Actual trend:  up  | Predicted trend:  up
Price 1 day before:  27.13
Actual price:  27.14  | Predicted price:  26.95713350892067
Actual trend:  up  | Predicted trend:  down
Correct counts:  2   Size of test set: 7

Calculating trend score for  2
Price 1 day before:  27.18
Actual price:  26.69  | Predicted price:  27.61142429113388
Actual trend:  down  | Predicted trend:  up
Price 1 day before:  26.69
Actual price:  26.74  | Predicted price:  27.179995771646496
Actual trend:  up  | Pre

'actual'

array([[27.18, 26.69, 26.74],
       [26.69, 26.74, 27.13],
       [26.74, 27.13, 27.14],
       [27.13, 27.14, 27.26],
       [27.14, 27.26, 27.96]])

'predicted'

array([[28.21148479, 27.61142429, 26.13483735],
       [27.84221353, 27.17999577, 25.60778106],
       [27.51931899, 26.81490275, 25.23253564],
       [27.30362715, 26.6493289 , 25.0504134 ],
       [26.95713351, 26.42151145, 25.05251354]])

t+1 RMSE: 0.782621
t+2 RMSE: 0.645868
t+3 RMSE: 1.982803
LSTM RMSE Score: US dollar [0.7826214331185234, 0.6458678596961541, 1.9828032213496793]


In [5]:
obj.save()
#obj.time()

In [6]:

saved_obj = load_saved_model("MU_nlag_1_nseq_1_ind_sma_train_01-04-2017_trainendteststart_10-04-2017_testend_20-04-2017")

In [7]:
saved_obj.input_tech_indicators_list.append("rsi")


In [8]:
saved_obj.n_lag = 5
saved_obj.preprocess_data()
saved_obj.input_tech_indicators_list = []
saved_obj.preprocess_data()



Preprocessing the data
Add from existing raw_pd  sma
Preprocessing the data
