In [1]:
# Normalise features
# Find the optimal parameters C (inverse regulalisation strengths)
# Find the best features to predict stock movement (up or down)
# Convert probability into absolute values (stock % increase/decrease)
# SVC, RandomForest, MinMax, LongShortTermMemory

%matplotlib inline
%pylab inline

# Nice Formatting within Jupyter Notebook
%matplotlib inline
from IPython.display import display # Allows multiple displays from a single code-cell
from jupyterthemes import jtplot

#import classes
from company import Company
from onestep_baseline_company import OneStepBaselineCompany
from onestep_lstm_company import OneStepLSTMCompany
from multistep_baseline_company import MultiStepBaselineCompany
from multistep_lstm_company import MultiStepLSTMCompany

jtplot.style(theme='grade3')
jtplot.style(theme='grade3')
jtplot.style(theme='grade3')


Populating the interactive namespace from numpy and matplotlib


Using TensorFlow backend.


In [ ]:
from multistep_lstm_company import MultiStepLSTMCompany
from alpha_vantage.techindicators import TechIndicators
from time import time
import pandas as pd
from sklearn.preprocessing import MinMaxScaler



class MultiStepLSTMCompanyTechIndicators(MultiStepLSTMCompany):
    def __init__(self, name, train_start_date_string, train_end_test_start_date_string, test_end_date_string,
                 n_lag, n_seq, n_epochs, n_batch, n_neurons, tech_indicators=[]):
        self.tech_indicators = TechIndicators(key='3OMS720IM6CRC3SV', output_format='pandas')
        self.all_tech_indicators = ["ad", "adosc", "adx", "adxr", "apo", "aroon", "aroonosc", 
                                    "bbands", "bop", "cci", "cmo", "dema", "dx", "ema", "ht_dcperiod", 
                                    "ht_dcphase", "ht_phasor", "ht_sine", "ht_trendline", "ht_trendmode", 
                                    "kama", "macd", "macdext", "mama", "mfi", "midpoint", "midprice", 
                                    "minus_di", "minus_dm", "mom", "natr", "obv", "plus_di", "plus_dm", 
                                    "ppo", "roc", "rocr", "rsi", "sar", "sma", "stoch", "stochf", "stochrsi", 
                                    "t3", "tema", "trange", "trima", "trix", "ultsoc", "willr", "wma"]
        if tech_indicators == "all":
            self.input_tech_indicators_list = self.all_tech_indicators
        else:
            self.input_tech_indicators_list = tech_indicators
        self.n_indicators = len(tech_indicators)
        #self.all_tech_indicators
        MultiStepLSTMCompany.__init__(self, name, train_start_date_string, train_end_test_start_date_string, test_end_date_string,
                 n_lag, n_seq, n_epochs, n_batch, n_neurons)
        
    
    def add_tech_indicators_dataframe(self, price_series, indicators):
        combined = price_series
        for ind in indicators:
            print("ind", ind)
            while True: # try again until success
                try:
                    ind_series = self.get_indicator(ind, self.train_start_date_string, self.test_end_date_string)
                    combined = pd.concat([combined, ind_series], axis=1)
                    break
                except:
                    print("Retrying to download indicator ", ind)
                    pass
        
        return combined

    def get_indicator(self, ind_name, start, end):
        data, meta_data = getattr(self.tech_indicators, "get_" + ind_name)(self.name, interval="daily")
        data.index = pd.to_datetime(data.index)
        data = self.get_filtered_series(data, start, end)
        return data
    
    def preprocess_data(self):
        price_series = self.train_raw_series.append(self.test_raw_series)
        display("price data series", len(price_series), price_series)
        if len(self.input_tech_indicators_list) > 0:
            #add additional technical indicators
            combined = self.add_tech_indicators_dataframe(price_series, self.input_tech_indicators_list)
        else:
            combined = price_series
        
        display("combined", combined)
            
        supervised_pd = self.timeseries_to_supervised(combined, self.n_lag, self.n_seq)
        display("supervised", supervised_pd)
        
        cutoff = len(self.train_raw_series) - self.n_seq - 1
        train_supervised_values = supervised_pd.values[:cutoff - self.n_lag + 1]
        display("train supervised values", train_supervised_values)
        test_supervised_values = supervised_pd.values[cutoff + self.n_seq - self.n_lag:]
        display("test supervised values", test_supervised_values)

        self.scaler, scaled_train_supervised, scaled_test_supervised = self.scale(train_supervised_values,
                                                                                  test_supervised_values)
        # delete unnecessary variables for prediction except price (should be var1)
        display("scaled train supervised", scaled_train_supervised)
        display("scaled test supervised", scaled_test_supervised)
        
        return scaled_train_supervised, scaled_test_supervised

    # evaluate the persistence model
    def predict(self):
        self.reset()
        # walk-forward validation on the test data
        predictions = pd.Series()
        # Index is datetime
        test_index = self.test_raw_series.index
        for i in range(len(self.test_scaled)):
            # make multi-step forecast
            X, y = self.test_scaled[i, 0:self.n_lag+self.n_indicators], self.test_scaled[i, self.n_lag+self.n_indicators:]
            print("X: ", X, "y: ", y)
            pred = self.forecast_lstm(X)
            print("Prediction: ", pred)
            # store forecast
            predictions.at[test_index[i]] = pred

        # display("predictions before inverse transform", predictions)
        # inverse transform
        predictions = self.inverse_transform(self.train_raw_series.append(self.test_raw_series), predictions,
                                             len(self.test_raw_series))
        print("Predictions after inverse transform")
        display(predictions)
        return predictions

    # scale train and test data to [-1, 1]
    def scale(self, train_raw, test_raw):
        # fit scaler with 1 Dimensional array data
        scaler = MinMaxScaler(feature_range=(-1, 1))
        # display("fit scaler with train data", scaler_train_data)
        scaler = scaler.fit(train_raw)
        # transform train
        train_scaled = scaler.transform(train_raw)
        # display("train_scaled", train_scaled)
        # transform test
        test_scaled = scaler.transform(test_raw)
        # display("test_scaled", test_scaled)

        return scaler, train_scaled, test_scaled
    
    # fit an LSTM network to training data
    def fit_lstm(self, train):
        # reshape training into [samples, timesteps, features]
        X, y = train[:, 0:self.n_lag+self.n_indicators], train[:, self.n_lag+self.n_indicators:]
        X = X.reshape(X.shape[0], 1, X.shape[1])
        display("train X data", X)
        display("train y data", y)
        # design network
        model = Sequential()
        model.add(LSTM(self.n_neurons, batch_input_shape=(self.n_batch, X.shape[1], X.shape[2]), stateful=True))
        model.add(Dense(y.shape[1]))
        model.compile(loss='mean_squared_error', optimizer='adam')
        # fit network
        for i in range(self.n_epochs):
            model.fit(X, y, epochs=1, batch_size=self.n_batch, verbose=0, shuffle=False)
            model.reset_states()
        return model
    


In [44]:
start_train_date = "01/01/2018"
end_train_start_test_date = "20/01/2018"
end_test_date = "01/02/2018"

multi_step_lstm_tech_indicator = MultiStepLSTMCompanyTechIndicators("MU", start_train_date, end_train_start_test_date, end_test_date, 
                         n_lag=2, n_seq=1, n_epochs=3000, n_batch=1, n_neurons=4, tech_indicators="all")

multi_step_lstm_tech_indicator.train()

'price data series'

22

date
2018-01-02    43.67
2018-01-03    44.98
2018-01-04    46.88
2018-01-05    45.80
2018-01-08    45.55
2018-01-09    42.97
2018-01-10    43.31
2018-01-11    42.82
2018-01-12    42.81
2018-01-16    42.92
2018-01-17    44.26
2018-01-18    43.99
2018-01-19    42.75
2018-01-22    42.88
2018-01-23    43.95
2018-01-24    43.08
2018-01-25    43.01
2018-01-26    43.67
2018-01-29    43.29
2018-01-30    41.67
2018-01-31    43.72
2018-02-01    42.49
Name: 5. adjusted close, dtype: float64

ind ad
ind adosc
ind adx
ind adxr
ind apo
ind aroon
ind aroonosc
ind bbands
ind bop
ind cci
ind cmo
ind dema
ind dx
ind ema
ind ht_dcperiod
ind ht_dcphase
ind ht_phasor
ind ht_sine
ind ht_trendline
ind ht_trendmode
ind kama
ind macd
ind macdext
ind mama
ind mfi
ind midpoint
ind midprice
ind minus_di
ind minus_dm
ind mom
ind natr
ind obv
ind plus_di
ind plus_dm
ind ppo
ind roc
ind rocr
ind rsi
ind sar
ind sma
ind stoch
ind stochf
ind stochrsi
ind t3
ind tema
ind trange
ind trima
ind trix
ind ultsoc
ind willr
ind wma


'combined'

5. adjusted close   Chaikin A/D         ADOSC      ADX     ADXR  \
date                                                                          
2018-01-02              43.67 -7.658382e+08 -1.956712e+07  17.2292  24.3007   
2018-01-03              44.98 -7.291121e+08 -1.310494e+06  16.7447  23.8563   
2018-01-04              46.88 -6.828422e+08  2.099952e+07  16.7505  23.6672   
2018-01-05              45.80 -6.984636e+08  2.324684e+07  16.7561  23.2246   
2018-01-08              45.55 -6.957786e+08  2.290716e+07  16.6082  22.5155   
2018-01-09              42.97 -7.492836e+08  3.661430e+06  15.8264  21.5947   
2018-01-10              43.31 -6.997159e+08  1.122685e+07  15.3452  20.9336   
2018-01-11              42.82 -7.270376e+08  4.607900e+06  14.7127  20.1772   
2018-01-12              42.81 -7.438434e+08 -3.866048e+06  14.1118  19.4714   
2018-01-16              42.92 -7.552658e+08 -1.061561e+07  13.4192  18.7401   
2018-01-17              44.26 -7.238909e+08 -2.428809e+06  12.9105  17.9145   
2018-01-18              43.99 -7.432675e+08 -5.024156e+06  12.5052  17.2088   
2018-01-19              42.75 -7.789705e+08 -1.698920e+07  12.0236  16.8398   
2018-01-22              42.88 -7.414409e+08 -8.398264e+06  11.8387  16.5366   
2018-01-23              43.95 -7.307877e+08 -7.306526e+05  11.3599  16.0259   
2018-01-24              43.08 -7.439078e+08 -1.702050e+06  10.9050  15.3941   
2018-01-25              43.01 -7.774567e+08 -1.261938e+07  10.6915  14.9032   
2018-01-26              43.67 -7.599035e+08 -1.035324e+07  10.4887  14.4774   
2018-01-29              43.29 -7.381395e+08 -1.560048e+06  10.0818  14.1042   
2018-01-30              41.67 -7.644638e+08 -6.196946e+06   9.7462  13.4877   
2018-01-31              43.72 -7.379523e+08  9.050000e+05   9.4525  13.0986   
2018-02-01              42.49 -7.591374e+08 -3.012642e+06   8.9976  12.8740   

               APO  Aroon Up  Aroon Down  AROONOSC  Real Upper Band   ...     \
date                                                                  ...      
2018-01-02 -0.2125      65.0         5.0      60.0          45.3354   ...      
2018-01-03  0.1966      60.0         0.0      60.0          45.4364   ...      
2018-01-04  0.6149     100.0         0.0     100.0          46.1215   ...      
2018-01-05  0.8710      95.0         0.0      95.0          46.4327   ...      
2018-01-08  0.9322      90.0        75.0      15.0          46.6841   ...      
2018-01-09  0.6783      85.0        70.0      15.0          46.6793   ...      
2018-01-10  0.5350      80.0        65.0      15.0          46.6866   ...      
2018-01-11  0.3144      75.0        60.0      15.0          46.6566   ...      
2018-01-12  0.2995      70.0        55.0      15.0          46.6337   ...      
2018-01-16  0.2846      65.0        50.0      15.0          46.6176   ...      
2018-01-17  0.4480      60.0        45.0      15.0          46.6588   ...      
2018-01-18  0.6572      55.0        40.0      15.0          46.6740   ...      
2018-01-19  0.5905      50.0        35.0      15.0          46.6464   ...      
2018-01-22  0.3763      45.0        30.0      15.0          46.3711   ...      
2018-01-23  0.0590      40.0        25.0      15.0          46.3270   ...      
2018-01-24 -0.1999      35.0        20.0      15.0          46.2705   ...      
2018-01-25 -0.4351      30.0        15.0      15.0          46.2582   ...      
2018-01-26 -0.3752      25.0        10.0      15.0          46.2728   ...      
2018-01-29 -0.3503      20.0         5.0      15.0          46.2217   ...      
2018-01-30 -0.2892      15.0         0.0      15.0          46.1472   ...      
2018-01-31 -0.1865      10.0         0.0      10.0          46.1496   ...      
2018-02-01 -0.1596       5.0        25.0     -20.0          46.0083   ...      

               FastD     FastK       T3     TEMA  TRANGE    TRIMA    TRIX  \
date                                                                        
2018-01-02   33.3333  100.0000  44.0750 

'supervised'

var1(t-2)     var2(t-2)     var3(t-2)  var4(t-2)  var5(t-2)  \
date                                                                      
2018-01-04      43.67 -7.658382e+08 -1.956712e+07    17.2292    24.3007   
2018-01-05      44.98 -7.291121e+08 -1.310494e+06    16.7447    23.8563   
2018-01-08      46.88 -6.828422e+08  2.099952e+07    16.7505    23.6672   
2018-01-09      45.80 -6.984636e+08  2.324684e+07    16.7561    23.2246   
2018-01-10      45.55 -6.957786e+08  2.290716e+07    16.6082    22.5155   
2018-01-11      42.97 -7.492836e+08  3.661430e+06    15.8264    21.5947   
2018-01-12      43.31 -6.997159e+08  1.122685e+07    15.3452    20.9336   
2018-01-16      42.82 -7.270376e+08  4.607900e+06    14.7127    20.1772   
2018-01-17      42.81 -7.438434e+08 -3.866048e+06    14.1118    19.4714   
2018-01-18      42.92 -7.552658e+08 -1.061561e+07    13.4192    18.7401   
2018-01-19      44.26 -7.238909e+08 -2.428809e+06    12.9105    17.9145   
2018-01-22      43.99 -7.432675e+08 -5.024156e+06    12.5052    17.2088   
2018-01-23      42.75 -7.789705e+08 -1.698920e+07    12.0236    16.8398   
2018-01-24      42.88 -7.414409e+08 -8.398264e+06    11.8387    16.5366   
2018-01-25      43.95 -7.307877e+08 -7.306526e+05    11.3599    16.0259   
2018-01-26      43.08 -7.439078e+08 -1.702050e+06    10.9050    15.3941   
2018-01-29      43.01 -7.774567e+08 -1.261938e+07    10.6915    14.9032   
2018-01-30      43.67 -7.599035e+08 -1.035324e+07    10.4887    14.4774   
2018-01-31      43.29 -7.381395e+08 -1.560048e+06    10.0818    14.1042   
2018-02-01      41.67 -7.644638e+08 -6.196946e+06     9.7462    13.4877   

            var6(t-2)  var7(t-2)  var8(t-2)  var9(t-2)  var10(t-2)    ...     \
date                                                                  ...      
2018-01-04    -0.2125       65.0        5.0       60.0     45.3354    ...      
2018-01-05     0.1966       60.0        0.0       60.0     45.4364    ...      
2018-01-08     0.6149      100.0        0.0      100.0     46.1215    ...      
2018-01-09     0.8710       95.0        0.0       95.0     46.4327    ...      
2018-01-10     0.9322       90.0       75.0       15.0     46.6841    ...      
2018-01-11     0.6783       85.0       70.0       15.0     46.6793    ...      
2018-01-12     0.5350       80.0       65.0       15.0     46.6866    ...      
2018-01-16     0.3144       75.0       60.0       15.0     46.6566    ...      
2018-01-17     0.2995       70.0       55.0       15.0     46.6337    ...      
2018-01-18     0.2846       65.0       50.0       15.0     46.6176    ...      
2018-01-19     0.4480       60.0       45.0       15.0     46.6588    ...      
2018-01-22     0.6572       55.0       40.0       15.0     46.6740    ...      
2018-01-23     0.5905       50.0       35.0       15.0     46.6464    ...      
2018-01-24     0.3763       45.0       30.0       15.0     46.3711    ...      
2018-01-25     0.0590       40.0       25.0       15.0     46.3270    ...      
2018-01-26    -0.1999       35.0       20.0       15.0     46.2705    ...      
2018-01-29    -0.4351       30.0       15.0       15.0     46.2582    ...      
2018-01-30    -0.3752       25.0       10.0       15.0     46.2728    ...      
2018-01-31    -0.3503       20.0        5.0       15.0     46.2217    ...      
2018-02-01    -0.2892       15.0        0.0       15.0     46.1472    ...      

            var56(t)  var57(t)  var58(t)  var59(t)  var60(t)  var61(t)  \
date                                                                     
2018-01-04  100.0000  100.0000   43.8475   43.8649    2.0000   43.2870   
2018-01-05   92.9963   78.9888   43.7759   44.3866    1.5048   43.3805   
2018-01-08   75.7042   48.1238   43.7338   44.7458    1.1800   43.4465   
2018-01-09   42.3709    0.0000   43.7102   44.3655    2.7800   43.4908   
2018-01-10   18.7098    8.0057   43.6983   44.1376    1.9800   43.5365   
2018-01-11    2.6686    0.0000   43.6912   43.8211    1.3800   43.5923   
2018-01-

'train supervised values'

array([[ 4.36700000e+01, -7.65838195e+08, -1.95671214e+07, ...,
         5.84113000e+01, -1.49700000e+00,  4.35436000e+01],
       [ 4.49800000e+01, -7.29112106e+08, -1.31049387e+06, ...,
         5.97692000e+01, -1.90016000e+01,  4.37878000e+01],
       [ 4.68800000e+01, -6.82842157e+08,  2.09995188e+07, ...,
         6.01755000e+01, -2.30274000e+01,  4.39880000e+01],
       ...,
       [ 4.28200000e+01, -7.27037599e+08,  4.60790016e+06, ...,
         4.25051000e+01, -6.53784000e+01,  4.36906000e+01],
       [ 4.28100000e+01, -7.43843389e+08, -3.86604799e+06, ...,
         4.89841000e+01, -4.38003000e+01,  4.37451000e+01],
       [ 4.29200000e+01, -7.55265806e+08, -1.06156097e+07, ...,
         4.64520000e+01, -4.81481000e+01,  4.37650000e+01]])

'test supervised values'

array([[ 4.42600000e+01, -7.23890886e+08, -2.42880943e+06, ...,
         4.83850000e+01, -6.81159000e+01,  4.36656000e+01],
       [ 4.39900000e+01, -7.43267519e+08, -5.02415557e+06, ...,
         4.73603000e+01, -6.60225000e+01,  4.35843000e+01],
       [ 4.27500000e+01, -7.78970542e+08, -1.69891993e+07, ...,
         5.11901000e+01, -4.87923000e+01,  4.36187000e+01],
       ...,
       [ 4.36700000e+01, -7.59903537e+08, -1.03532400e+07, ...,
         4.64422000e+01, -9.17098000e+01,  4.33130000e+01],
       [ 4.32900000e+01, -7.38139467e+08, -1.56004778e+06, ...,
         4.84348000e+01, -5.83184000e+01,  4.33137000e+01],
       [ 4.16700000e+01, -7.64463837e+08, -6.19694607e+06, ...,
         4.36211000e+01, -8.03220000e+01,  4.31970000e+01]])

'scaled train supervised'

array([[-0.57739558, -1.        , -1.        , ...,  0.80032144,
         1.        , -1.        ],
       [ 0.06633907, -0.11499175, -0.14716474, ...,  0.95401349,
         0.46675237,  0.0990099 ],
       [ 1.        ,  1.        ,  0.89501928, ...,  1.        ,
         0.34411327,  1.        ],
       ...,
       [-0.995086  , -0.06500125,  0.12930555, ..., -1.        ,
        -0.94603734, -0.33843384],
       [-1.        , -0.46997936, -0.26654422, ..., -0.26668327,
        -0.28869751, -0.09315932],
       [-0.94594595, -0.74523146, -0.58184146, ..., -0.55327553,
        -0.42114579, -0.00360036]])

'scaled test supervised'

array([[-0.28746929,  0.0108268 , -0.19940544, ..., -0.33449158,
        -1.02943058, -0.45094509],
       [-0.42014742, -0.45610233, -0.32064375, ..., -0.45047084,
        -0.96565874, -0.81683168],
       [-1.02948403, -1.31645719, -0.87957563, ..., -0.01700018,
        -0.44077023, -0.6620162 ],
       ...,
       [-0.57739558, -0.85698937, -0.56958519, ..., -0.55438473,
        -1.7481783 , -2.03780378],
       [-0.76412776, -0.33252891, -0.15882234, ..., -0.32885503,
        -0.73096654, -2.03465347],
       [-1.56019656, -0.96688135, -0.37542918, ..., -0.87368707,
        -1.40126849, -2.55985599]])

Fitting the model


'train X data'

array([[[-0.57739558, -1.        , -1.        ,  1.        ,
          1.        ]],

       [[ 0.06633907, -0.11499175, -0.14716474,  0.74566929,
          0.84016113]],

       [[ 1.        ,  1.        ,  0.89501928,  0.74871391,
          0.77214689]],

       [[ 0.46928747,  0.62356196,  1.        ,  0.75165354,
          0.61295544]],

       [[ 0.34643735,  0.68826338,  0.98413234,  0.67401575,
          0.35791102]],

       [[-0.92137592, -0.60107399,  0.08509241,  0.26362205,
          0.02672373]],

       [[-0.75429975,  0.59338447,  0.43850134,  0.01102362,
         -0.21105636]],

       [[-0.995086  , -0.06500125,  0.12930555, -0.32099738,
         -0.48311333]],

       [[-1.        , -0.46997936, -0.26654422, -0.63643045,
         -0.73697083]],

       [[-0.94594595, -0.74523146, -0.58184146, -1.        ,
         -1.        ]]])

'train y data'

array([[-1.        , -0.75      , -0.86666667, ...,  0.80032144,
         1.        , -1.        ],
       [-0.28522757, -1.        , -1.        , ...,  0.95401349,
         0.46675237,  0.0990099 ],
       [ 0.44561894,  1.        , -1.        , ...,  1.        ,
         0.34411327,  1.        ],
       ...,
       [-0.07940945, -0.25      ,  0.6       , ..., -1.        ,
        -0.94603734, -0.33843384],
       [-0.10544247, -0.5       ,  0.46666667, ..., -0.26668327,
        -0.28869751, -0.09315932],
       [-0.1314755 , -0.75      ,  0.33333333, ..., -0.55327553,
        -0.42114579, -0.00360036]])

NameError: name 'Sequential' is not defined

In [26]:
#multi_step_lstm_tech_indicator.tech_indicators.__dict__.keys()
print(multi_step_lstm_tech_indicator.all_tech_indicators)
#data = multi_step_lstm_tech_indicator.get_rsi()
#X, y = multi_step_lstm_tech_indicator.train_scaled[:, 0:multi_step_lstm_tech_indicator.n_lag], multi_step_lstm_tech_indicator.train_scaled[:, multi_step_lstm_tech_indicator.n_lag:]
#X = X.reshape(X.shape[0], 1, X.shape[1])

['ad', 'adosc', 'adx', 'adxr', 'apo', 'aroon', 'aroonosc', 'bbands', 'bop', 'cci', 'cmo', 'dema', 'dx', 'ema', 'ht_dcperiod', 'ht_dcphase', 'ht_phasor', 'ht_sine', 'ht_trendline', 'ht_trendmode', 'kama', 'macd', 'macdext', 'mama', 'mfi', 'midpoint', 'midprice', 'minus_di', 'minus_dm', 'mom', 'natr', 'obv', 'plus_di', 'plus_dm', 'ppo', 'roc', 'rocr', 'rsi', 'sar', 'sma', 'stoch', 'stochf', 'stochrsi', 't3', 'tema', 'trange', 'trima', 'trix', 'ultsoc', 'willr', 'wma']


In [ ]:
#import numpy as np
#import pandas as pd
display(multi_step_lstm_tech_indicator)

display("size", len(data.values), " values:", data.values[1:-1])
display("size", len(X), " values:", X)
display(np.concatenate((X, data.values[1:-1]), axis=1))
#display(pd.concat([price, data], axis=1))