In [ ]:
import numpy as np
import csv
import os
from multistep_lstm_company import MultiStepLSTMCompany
from datetime import date
import math


def get_optimal_epochs_batch_neurons_params(symbol, start_train_date, end_train_start_test_date, end_test_date, n_lags, n_seqs,
                                            n_epochs, n_batches, n_neurons, indicators, model_types):
    # This is optimising parameters for n_epochs, n_batch, and n_neurons
    # param = {"n_epochs": n_epochs, "n_batch": n_batch, "n_neurons": n_neurons}
    csv_columns = ["Company", "LSTM Type", "n_epoch", "n_neuros", "n_batch",
                   "n_lag", "n_seq", "Training Time",
                   "Indicator Number", "Indicators", "Trained Date",
                   "Start Train Date", "End Train/Start Test Date", "End Test Date",
                   "Model Name"]
    for i in range(30):
        csv_columns.append("Trend_t+" + str(i+1))
        csv_columns.append("APRE_t+" + str(i+1))
        csv_columns.append("RMSE_t+" + str(i+1))

    if not os.path.isdir("./experiments"):
        # create directory
        os.mkdir("experiments")

    filename = "./experiments/optimisation.csv"
    if not os.path.isfile(filename):
        # create new file
        with open(filename, "w", newline="") as csvfile:
            writer = csv.DictWriter(csvfile, fieldnames=csv_columns)
            writer.writeheader()

    for n_e in n_epochs:
        for n_b in n_batches:
            for n_n in n_neurons:
                for n_l in n_lags:
                    for n_s in n_seqs:
                        for m_t in model_types:
                            print("In process of training", symbol, "model type:", m_t, "n_lag:",
                                  n_l, "n_seq:", n_s, "n_epoch:", n_e, "n_batch:", n_b, "n_neurons:", n_n)
                            obj = MultiStepLSTMCompany(symbol, start_train_date, end_train_start_test_date,
                                                       end_test_date, n_lag=n_l, n_seq=n_s, n_epochs=n_e,
                                                       n_neurons=n_n, n_batch=n_b, tech_indicators=indicators,
                                                       model_type=m_t)
                            obj.train()
                            predictions = obj.predict()
                            trend_score = obj.score(metric="trend", predictions=predictions)
                            lstm_score = obj.score(metric="rmse", predictions=predictions)
                            apre_score = obj.score(metric="apre", predictions=predictions)

                            dic = {"Company": symbol,
                                   "LSTM Type": obj.model_type,
                                   "n_epoch": obj.n_epochs,
                                   "n_neuros": obj.n_neurons,
                                   "n_batch": obj.n_batch,
                                   "n_lag": obj.n_lag,
                                   "n_seq": obj.n_seq,
                                   "Training Time": obj.time_taken_to_train,
                                   "Start Train Date": obj.train_start_date_string,
                                   "End Train/Start Test Date": obj.train_end_test_start_date_string,
                                   "End Test Date": obj.test_end_date_string,
                                   "Indicator Number": len(obj.input_tech_indicators_list) + 1,
                                   "Indicators": "Share Price," + ",".join(obj.input_tech_indicators_list),
                                   "Trained Date": str(date.today()),
                                    "Model Name": obj.create_file_name()}
                            for i in range(n_s):
                                dic["Trend_t+" + str(i+1)] = trend_score[i]
                                dic["APRE_t+" + str(i+1)] = apre_score[i]
                                dic["RMSE_t+" + str(i+1)] = lstm_score[i]

                            append_dict_to_csv(filename, csv_columns, dic)

def append_dict_to_csv(csv_file_name, csv_columns, dic):
    with open(csv_file_name, 'a', newline='') as csvfile:
        writer = csv.DictWriter(csvfile, fieldnames=csv_columns)
        writer.writerow(dic)


n_lags = [5]
n_seqs = [3]
n_epochs = np.logspace(math.log(100, 10), math.log(5000, 10), num=10).astype(int)
n_neurons = np.logspace(math.log(1, 10), math.log(52, 10), num=10).astype(int)
n_batches = ["full_batch"]#, "half_batch", "online"]
#http://firsttimeprogrammer.blogspot.com/2015/09/selecting-number-of-neurons-in-hidden.html?m=1

indicators = "all"
model_types = ["vanilla", "stacked", "stacked", "bi", "cnn", "conv"] # ["vanilla", "stacked", "stacked", "bi", "cnn", "conv"] #
start_train_date = "01/01/2016"
end_train_start_test_date = "01/01/2018"
end_test_date = "01/01/2019"
pred = get_optimal_epochs_batch_neurons_params("AMZN", start_train_date, end_train_start_test_date, end_test_date, n_lags, n_seqs, n_epochs, n_batches, n_neurons, indicators, model_types)

Using TensorFlow backend.


Preprocessing the data
Retrieved price series and raw pd from disk


'supervised filtered pd '

Share Price(t-5)       AD(t-5)    ADOSC(t-5)  ADX(t-5)  ADXR(t-5)  \
date                                                                            
1998-06-25           -0.0254 -7.758414e+05 -3.058647e+05   -0.4751    -0.5987   
1998-06-26           -0.0079 -1.246000e+05 -1.370203e+05   -0.2236    -0.6879   
1998-06-29            0.0098  6.378333e+05  1.871012e+05   -0.2868    -0.5296   
1998-06-30            0.0138  5.928161e+05  2.883635e+05   -0.6110    -0.4637   
1998-07-01            0.0138  1.063681e+06  4.533947e+05   -0.4366    -0.6405   
1998-07-02            0.0097  0.000000e+00  1.412459e+05   -0.3107    -0.4916   
1998-07-06           -0.0116  1.140345e+04  4.336466e+03   -0.5927    -0.4525   
1998-07-07            0.0157  1.008984e+06  2.653458e+05   -0.4907    -0.3936   
1998-07-08            0.0000  7.631739e+05  2.697877e+05   -0.4661    -0.3740   
1998-07-09            0.0393  2.580232e+06  8.252336e+05    0.2089     0.0495   
1998-07-10           -0.0295 -2.661700e+06 -6.904473e+05    0.2283    -0.0503   
1998-07-13            0.0430  2.419200e+06  3.689194e+05    0.3718    -0.0960   
1998-07-14            0.0041  3.221609e+05  1.015189e+05    0.5919    -0.1866   
1998-07-15            0.0647  5.515450e+06  1.635309e+06    1.3421     0.3063   
1998-07-16           -0.0274 -3.903977e+06 -8.829864e+05    1.4784     0.3928   
1998-07-17            0.0117 -7.980523e+05 -8.446779e+05    1.4045     0.2752   
1998-07-20            0.0590  5.313412e+06  1.192340e+06    1.7284     0.4904   
1998-07-21           -0.0157 -1.407356e+06 -2.211559e+05    1.6419     0.4660   
1998-07-22            0.0314  3.080183e+06  6.485545e+05    1.7216     0.5654   
1998-07-23            0.0961  1.076198e+07  3.389593e+06    2.2247     0.8747   
1998-07-24           -0.0195  1.696906e+06  1.318441e+06    2.1134     0.9450   
1998-07-27           -0.0198  1.122312e+06  1.684678e+05    1.5598     0.6365   
1998-07-28           -0.0194 -2.655972e+06 -1.519472e+06    1.5456     0.4673   
1998-07-29           -0.0198  2.179565e+05 -1.157427e+06    0.6829     0.1231   
1998-07-30           -0.0019 -1.284148e+06 -1.382040e+06    0.6487     0.1690   
1998-07-31           -0.0078  1.003278e+05 -9.077716e+05    0.0950    -0.2488   
1998-08-03           -0.0079  8.801227e+05 -3.831116e+05   -0.1994    -0.3451   
1998-08-04           -0.0254 -4.567798e+05 -5.590277e+05   -0.3170    -0.3916   
1998-08-05            0.0471  1.259486e+06 -3.408805e+04    0.0653     0.1371   
1998-08-06            0.0430  1.940880e+06  4.005660e+05    0.2886     0.2585   
...                      ...           ...           ...       ...        ...   
2018-11-15           -0.7243  8.278605e+05  2.194162e+06    0.1807    -0.4423   
2018-11-16           -4.0029  6.215082e+06  6.273133e+05    0.4507    -0.2807   
2018-11-19          -10.2560 -4.472248e+07 -1.627811e+07    0.8742    -0.1115   
2018-11-20           -1.9318 -3.412041e+07 -1.834074e+07    0.9398    -0.0513   
2018-11-21           -5.4068 -4.842743e+07 -2.206944e+07    1.1327     0.4135   
2018-11-23            4.5903  3.621129e+07  5.341995e+06    1.0762     0.2972   
2018-11-26            2.1110  1.763132e+07  1.015832e+07    0.6794    -0.0174   
2018-11-27           -7.6373 -2.914639e+07 -3.678665e+06    0.8538     0.3008   
2018-11-28           -8.8421 -3.436783e+07 -1.066619e+07    1.1868     0.4127   
2018-11-29           -0.1992 -2.727552e+07 -1.029843e+07    1.1274     0.3921   
2018-11-30           -4.4708 -2.162684e+07 -7.414454e+06    1.2295     0.6512   
2018-12-03            2.3201  3.866611e+07  1.362351e+07    1.2308     0.9174   
2018-12-04           -0.3784  3.010958e+07  1.826893e+07    1.1693     0.8715   
2018-12-06            6.6714  4.099276e+07  2.197134e+07    0.3576     0.1097   
2018-12-07           -1.3841 -1.146627e+07  4.797057e+06    0.1778    -0.0890   
2018-12-10           -0.9658 -2.395851e+06  2.211616e+05    0.2025     0.3618   
2018-12-11            6.2133  3.817293e+07 

'test supervised values'

array([[ 0.00000000e+00,  1.66780416e+06, -6.44569745e+05, ...,
         2.97250000e+00, -2.95000000e-02,  7.84900000e-01],
       [-4.35580000e+00, -1.65669181e+05, -8.15503647e+05, ...,
        -2.95000000e-02,  7.84900000e-01,  1.93260000e+00],
       [ 2.95000000e-02,  1.43805271e+07,  3.81704073e+06, ...,
         7.84900000e-01,  1.93260000e+00, -6.37700000e-01],
       ...,
       [-5.15790000e+00, -2.79264514e+07, -7.02369781e+06, ...,
        -1.01570000e+00,  7.97000000e-02,  1.50360000e+00],
       [-4.04270000e+00, -3.56679295e+07, -1.09380715e+07, ...,
         7.97000000e-02,  1.50360000e+00,  1.79200000e-01],
       [-6.07390000e+00, -7.10506390e+07, -2.28031708e+07, ...,
         1.50360000e+00,  1.79200000e-01, -1.56629000e+01]])

Preprocessed data in  0.010910336176554363 mins
Fitting the model
train X size 4912  train X data dimension (4912, 5, 52) train y size 4912  train X data dimension (4912, 3)
Training model with batch size 4912
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_1 (LSTM)                (4912, 1)                 216       
_________________________________________________________________
dense_1 (Dense)              (4912, 3)                 6         
Total params: 222
Trainable params: 222
Non-trainable params: 0
_________________________________________________________________


New model with batch size 1 for prediction
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_2 (LSTM)                (1, 1)                    216       
_________________________________________________________________
dense_2 (Dense)      

'Len(predictions)'

251

2018-01-02     [0.024825256, 0.03713826, 0.0055663027]
2018-01-03      [0.03704686, 0.044518873, 0.026067372]
2018-01-04      [0.036134977, 0.04396819, 0.024537737]
2018-01-05     [0.039557412, 0.046034995, 0.030278686]
2018-01-08        [0.0725749, 0.06597422, 0.085663706]
2018-01-09       [0.04680986, 0.05041474, 0.042444266]
2018-01-10      [0.055514142, 0.055671245, 0.05704522]
2018-01-11        [0.07684396, 0.06855231, 0.09282483]
2018-01-12      [0.061424468, 0.059240486, 0.06695947]
2018-01-16        [0.06735689, 0.06282307, 0.07691078]
2018-01-17      [0.029721241, 0.04009494, 0.013779048]
2018-01-18       [0.06459017, 0.061152253, 0.07226977]
2018-01-19        [0.07232131, 0.06582108, 0.08523832]
2018-01-22     [0.053063013, 0.054191012, 0.052933585]
2018-01-23       [0.05948942, 0.05807191, 0.063713536]
2018-01-24       [0.068538435, 0.06353661, 0.07889276]
2018-01-25      [0.03920406, 0.045821607, 0.029685957]
2018-01-26     [0.034562934, 0.043018833, 0.021900719]
2018-01-29

'Len(actual)'

249

array([[ 2.97250e+00, -2.95000e-02,  7.84900e-01],
       [-2.95000e-02,  7.84900e-01,  1.93260e+00],
       [ 7.84900e-01,  1.93260e+00, -6.37700e-01],
       [ 1.93260e+00, -6.37700e-01, -1.96000e-02],
       [-6.37700e-01, -1.96000e-02, -3.93000e-02],
       [-1.96000e-02, -3.93000e-02,  9.71200e-01],
       [-3.93000e-02,  9.71200e-01,  1.77570e+00],
       [ 9.71200e-01,  1.77570e+00, -8.82900e-01],
       [ 1.77570e+00, -8.82900e-01,  2.85470e+00],
       [-8.82900e-01,  2.85470e+00,  1.57000e-01],
       [ 2.85470e+00,  1.57000e-01, -7.84800e-01],
       [ 1.57000e-01, -7.84800e-01, -1.43230e+00],
       [-7.84800e-01, -1.43230e+00,  3.92000e-02],
       [-1.43230e+00,  3.92000e-02, -2.76640e+00],
       [ 3.92000e-02, -2.76640e+00, -3.05100e+00],
       [-2.76640e+00, -3.05100e+00,  3.92400e-01],
       [-3.05100e+00,  3.92400e-01, -3.48260e+00],
       [ 3.92400e-01, -3.48260e+00, -9.71200e-01],
       [-3.48260e+00, -9.71200e-01,  4.51300e-01],
       [-9.71200e-01,  4.51300e

'Len(predictions)'

249

array([[ -2.07905377,  -2.24966626,  -2.66012933],
       [  2.80119315,   2.6866508 ,   2.43193333],
       [ -0.20773439,  -0.32646025,  -0.59279829],
       [  0.63266568,   0.52964124,   0.30691691],
       [  2.03119788,   2.07965073,   2.27768362],
       [ -0.73483784,  -0.80458957,  -0.9348926 ],
       [ -0.05061184,  -0.08043018,  -0.09981048],
       [  0.09172974,   0.15976819,   0.4122038 ],
       [  0.98508861,   0.98238562,   1.03832337],
       [  1.83465694,   1.85917068,   1.99070802],
       [ -1.10985921,  -1.25800995,  -1.60608121],
       [  2.8926383 ,   2.90445891,   3.00073872],
       [  0.25367138,   0.30096085,   0.49576212],
       [ -0.83443295,  -0.87549654,  -0.92611274],
       [ -1.43311184,  -1.44469243,  -1.41341389],
       [  0.10713306,   0.13706749,   0.28366184],
       [ -2.92131871,  -3.02596425,  -3.25319152],
       [ -3.24117712,  -3.3671152 ,  -3.65348653],
       [  0.43112806,   0.4434256 ,   0.54103017],
       [ -3.54994376,  -3.60170


Calculating trend score for  1
Correct counts:  112   Size of test set: 251

Calculating trend score for  2
Correct counts:  169   Size of test set: 251

Calculating trend score for  3
Correct counts:  159   Size of test set: 251


'Len(actual)'

249

array([[ 2.97250e+00, -2.95000e-02,  7.84900e-01],
       [-2.95000e-02,  7.84900e-01,  1.93260e+00],
       [ 7.84900e-01,  1.93260e+00, -6.37700e-01],
       [ 1.93260e+00, -6.37700e-01, -1.96000e-02],
       [-6.37700e-01, -1.96000e-02, -3.93000e-02],
       [-1.96000e-02, -3.93000e-02,  9.71200e-01],
       [-3.93000e-02,  9.71200e-01,  1.77570e+00],
       [ 9.71200e-01,  1.77570e+00, -8.82900e-01],
       [ 1.77570e+00, -8.82900e-01,  2.85470e+00],
       [-8.82900e-01,  2.85470e+00,  1.57000e-01],
       [ 2.85470e+00,  1.57000e-01, -7.84800e-01],
       [ 1.57000e-01, -7.84800e-01, -1.43230e+00],
       [-7.84800e-01, -1.43230e+00,  3.92000e-02],
       [-1.43230e+00,  3.92000e-02, -2.76640e+00],
       [ 3.92000e-02, -2.76640e+00, -3.05100e+00],
       [-2.76640e+00, -3.05100e+00,  3.92400e-01],
       [-3.05100e+00,  3.92400e-01, -3.48260e+00],
       [ 3.92400e-01, -3.48260e+00, -9.71200e-01],
       [-3.48260e+00, -9.71200e-01,  4.51300e-01],
       [-9.71200e-01,  4.51300e

'Len(predictions)'

249

array([[ -2.07905377,  -2.24966626,  -2.66012933],
       [  2.80119315,   2.6866508 ,   2.43193333],
       [ -0.20773439,  -0.32646025,  -0.59279829],
       [  0.63266568,   0.52964124,   0.30691691],
       [  2.03119788,   2.07965073,   2.27768362],
       [ -0.73483784,  -0.80458957,  -0.9348926 ],
       [ -0.05061184,  -0.08043018,  -0.09981048],
       [  0.09172974,   0.15976819,   0.4122038 ],
       [  0.98508861,   0.98238562,   1.03832337],
       [  1.83465694,   1.85917068,   1.99070802],
       [ -1.10985921,  -1.25800995,  -1.60608121],
       [  2.8926383 ,   2.90445891,   3.00073872],
       [  0.25367138,   0.30096085,   0.49576212],
       [ -0.83443295,  -0.87549654,  -0.92611274],
       [ -1.43311184,  -1.44469243,  -1.41341389],
       [  0.10713306,   0.13706749,   0.28366184],
       [ -2.92131871,  -3.02596425,  -3.25319152],
       [ -3.24117712,  -3.3671152 ,  -3.65348653],
       [  0.43112806,   0.4434256 ,   0.54103017],
       [ -3.54994376,  -3.60170

t+1 RMSE: 4.685704
t+2 RMSE: 4.951855
t+3 RMSE: 4.944601


'Len(actual)'

249

array([[ 2.97250e+00, -2.95000e-02,  7.84900e-01],
       [-2.95000e-02,  7.84900e-01,  1.93260e+00],
       [ 7.84900e-01,  1.93260e+00, -6.37700e-01],
       [ 1.93260e+00, -6.37700e-01, -1.96000e-02],
       [-6.37700e-01, -1.96000e-02, -3.93000e-02],
       [-1.96000e-02, -3.93000e-02,  9.71200e-01],
       [-3.93000e-02,  9.71200e-01,  1.77570e+00],
       [ 9.71200e-01,  1.77570e+00, -8.82900e-01],
       [ 1.77570e+00, -8.82900e-01,  2.85470e+00],
       [-8.82900e-01,  2.85470e+00,  1.57000e-01],
       [ 2.85470e+00,  1.57000e-01, -7.84800e-01],
       [ 1.57000e-01, -7.84800e-01, -1.43230e+00],
       [-7.84800e-01, -1.43230e+00,  3.92000e-02],
       [-1.43230e+00,  3.92000e-02, -2.76640e+00],
       [ 3.92000e-02, -2.76640e+00, -3.05100e+00],
       [-2.76640e+00, -3.05100e+00,  3.92400e-01],
       [-3.05100e+00,  3.92400e-01, -3.48260e+00],
       [ 3.92400e-01, -3.48260e+00, -9.71200e-01],
       [-3.48260e+00, -9.71200e-01,  4.51300e-01],
       [-9.71200e-01,  4.51300e

'Len(predictions)'

249

array([[ -2.07905377,  -2.24966626,  -2.66012933],
       [  2.80119315,   2.6866508 ,   2.43193333],
       [ -0.20773439,  -0.32646025,  -0.59279829],
       [  0.63266568,   0.52964124,   0.30691691],
       [  2.03119788,   2.07965073,   2.27768362],
       [ -0.73483784,  -0.80458957,  -0.9348926 ],
       [ -0.05061184,  -0.08043018,  -0.09981048],
       [  0.09172974,   0.15976819,   0.4122038 ],
       [  0.98508861,   0.98238562,   1.03832337],
       [  1.83465694,   1.85917068,   1.99070802],
       [ -1.10985921,  -1.25800995,  -1.60608121],
       [  2.8926383 ,   2.90445891,   3.00073872],
       [  0.25367138,   0.30096085,   0.49576212],
       [ -0.83443295,  -0.87549654,  -0.92611274],
       [ -1.43311184,  -1.44469243,  -1.41341389],
       [  0.10713306,   0.13706749,   0.28366184],
       [ -2.92131871,  -3.02596425,  -3.25319152],
       [ -3.24117712,  -3.3671152 ,  -3.65348653],
       [  0.43112806,   0.4434256 ,   0.54103017],
       [ -3.54994376,  -3.60170

t+1 APRE: -0.633255
t+2 APRE: 0.666891
t+3 APRE: 2.081457


(4912, 263)

array([[ 0.05959629,  0.1684831 ,  0.15942954, ...,  0.45087173,
         0.05571315,  0.16291406],
       [-0.51376539,  0.15402169,  0.15592674, ...,  0.05571315,
         0.16291406,  0.31398785],
       [ 0.06347942,  0.26875388,  0.2508574 , ...,  0.16291406,
         0.31398785, -0.0243453 ],
       ...,
       [-0.61934724, -0.06493969,  0.02870768, ..., -0.07410211,
         0.07008734,  0.25751782],
       [-0.47255148, -0.1260001 , -0.05150614, ...,  0.07008734,
         0.25751782,  0.0831847 ],
       [-0.73992194, -0.40507894, -0.29464718, ...,  0.25751782,
         0.0831847 , -2.00213902]])

(4912,)

date
2018-01-02     2.9725
2018-01-03    -0.0295
2018-01-04     0.7849
2018-01-05     1.9326
2018-01-08    -0.6377
2018-01-09    -0.0196
2018-01-10    -0.0393
2018-01-11     0.9712
2018-01-12     1.7757
2018-01-16    -0.8829
2018-01-17     2.8547
2018-01-18     0.1570
2018-01-19    -0.7848
2018-01-22    -1.4323
2018-01-23     0.0392
2018-01-24    -2.7664
2018-01-25    -3.0510
2018-01-26     0.3924
2018-01-29    -3.4826
2018-01-30    -0.9712
2018-01-31     0.4513
2018-02-01     0.3433
2018-02-02    -7.1418
2018-02-05    -3.9339
2018-02-06     6.4159
2018-02-07    -3.4238
2018-02-08    -4.3067
2018-02-09     1.8542
2018-02-12     6.2053
2018-02-13     1.6055
               ...   
2018-11-15     4.5903
2018-11-16     2.1110
2018-11-19    -7.6373
2018-11-20    -8.8421
2018-11-21    -0.1992
2018-11-23    -4.4708
2018-11-26     2.3201
2018-11-27    -0.3784
2018-11-28     6.6714
2018-11-29    -1.3841
2018-11-30    -0.9658
2018-12-03     6.2133
2018-12-04    -8.0953
2018-12-06    -1.9616
2018-